version: 2

jobs:
  deploy-staging:
    docker:
      - image: circleci/php:cli
    steps:
      - run:
          name: SSH and deploy to staging
          command: ssh -oStrictHostKeyChecking=no ops@51.158.72.176 -p 19090 "cd /home/ops/docker-build/gantigol-fe-staging/ && sh deploy.sh master"

workflows:
  version: 2
  build_and_deploy_staging:
    jobs:
      - deploy-staging:
          filters:
            branches:
              only: master